source "https://rubygems.org"

gemspec :path => "../"
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# For LiveReload: https://robbinespu.gitlab.io/posts/jekyll-unable-load-eventmachine/
gem 'eventmachine', '1.2.7', github: 'eventmachine/eventmachine', tag: 'v1.2.7'


